# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WDChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WDChat

  target 'WDChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WDChatUITests' do
    # Pods for testing
  end

end

pod 'SnapKit'