# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WDChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'SVGAPlayer'
  pod 'HandyJSON'
  pod 'KakaJSON'



end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
